# Generated by Django 5.2.1 on 2025-06-03 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="modules", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="module",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="module",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="module",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
